In [1]:
#Import dependants
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from pathlib import Path

In [8]:
CSV1Kpath = Path("Kaggle1DS.csv")
CSV2Kpath = Path("Kaggle2DS.csv")
CSV3Xpath = Path("SHD.csv")
CSV1KR = pd.read_csv(CSV1Kpath)
CSV2KR = pd.read_csv(CSV2Kpath)
CSV3XR = pd.read_csv(CSV3Xpath)

Firstm = pd.merge(CSV1KR, CSV2KR, on="school")
Data = pd.merge(Firstm, CSV3XR, on= "school")

# output DataFrame as CSV to view easier
output_path = "Outputs/merged_df.csv"
Data.to_csv(output_path)

In [9]:
Firstm.head()

,LONCOD,LATCOD,CDCODE,year_x,school,city_x,state_x,address,urbanrural,race,...,lat,long,staffing,low_grade,high_grade,lunch,county,state_fips,county_fips,ulocale
0,-75.584900,39.668100,1000.0,2009,William Penn High School,New Castle,Delaware,713 E Basin Rd,suburbtown,BLACK,...,39.668622,-75.584879,128.0,9,12,NaN,New Castle County,10,10003,21.0
1,-83.113977,42.383593,NaN,2009,Central High School,Detroit,Michigan,2425 Tuxedo St,urban,NaN,...,42.384690,-83.112690,55.2,8,12,897,Wayne County,26,26163,11.0
2,-83.113977,42.383593,NaN,2009,Central High School,Detroit,Michigan,2425 Tuxedo St,urban,NaN,...,36.039200,-83.921600,79.5,9,12,569,Knox County,47,47093,12.0
3,-83.113977,42.383593,NaN,2009,Central High School,Detroit,Michigan,2425 Tuxedo St,urban,NaN,...,42.383700,-83.111500,57.2,9,12,640,Wayne County,26,26163,11.0
4,-93.773980,32.503605,2204.0,2009,Booker T. Washington High School,Shreveport,Louisiana,2104 Milam St,urban,BLACK,...,29.949660,-90.088930,36.8,8,12,308,Orleans Parish,22,22071,11.0

In [10]:
Firstm.columns

Index(['LONCOD', 'LATCOD', 'CDCODE', 'year_x', 'school', 'city_x', 'state_x',
       'address', 'urbanrural', 'race', 'killed_x', 'injured_x', 'victims',
       'date_x', 'type', 'NCESSCH', 'time_x', 'uid', 'nces_school_id',
       'nces_district_id', 'district_name', 'date_y', 'school_year', 'year_y',
       'time_y', 'day_of_week', 'city_y', 'state_y', 'school_type',
       'enrollment', 'killed_y', 'injured_y', 'casualties', 'shooting_type',
       'age_shooter1', 'gender_shooter1', 'race_ethnicity_shooter1',
       'shooter_relationship1', 'shooter_deceased1', 'deceased_notes1',
       'age_shooter2', 'gender_shooter2', 'race_ethnicity_shooter2',
       'shooter_relationship2', 'shooter_deceased2', 'deceased_notes2',
       'white', 'black', 'hispanic', 'asian', 'american_indian_alaska_native',
       'hawaiian_native_pacific_islander', 'two_or_more', 'resource_officer',
       'weapon', 'weapon_source', 'lat', 'long', 'staffing', 'low_grade',
       'high_grade', 'lunch', 'county', 'state_fips', 'county_fips',
       'ulocale'],
      dtype='object')

In [5]:
Data.columns

Index(['LONCOD', 'LATCOD', 'CDCODE', 'year_x', 'school', 'city_x', 'state_x',
       'address', 'urbanrural', 'race', 'killed_x', 'injured_x', 'victims',
       'date_x', 'type', 'NCESSCH', 'time_x', 'uid', 'nces_school_id',
       'nces_district_id', 'district_name', 'date_y', 'school_year', 'year_y',
       'time_y', 'day_of_week', 'city_y', 'state_y', 'school_type',
       'enrollment', 'killed_y', 'injured_y', 'casualties', 'shooting_type',
       'age_shooter1', 'gender_shooter1', 'race_ethnicity_shooter1',
       'shooter_relationship1', 'shooter_deceased1', 'deceased_notes1',
       'age_shooter2', 'gender_shooter2', 'race_ethnicity_shooter2',
       'shooter_relationship2', 'shooter_deceased2', 'deceased_notes2',
       'white', 'black', 'hispanic', 'asian', 'american_indian_alaska_native',
       'hawaiian_native_pacific_islander', 'two_or_more', 'resource_officer',
       'weapon', 'weapon_source', 'lat', 'long', 'staffing', 'low_grade',
       'high_grade', 'lunch', 'county', 'state_fips', 'county_fips', 'ulocale',
       'Incident_ID', 'Date', 'Quarter', 'City', 'State', 'School_Level',
       'Location', 'During_School', 'Time_Period', 'First_Shot', 'Bullied',
       'Domestic_Violence', 'Gang_Related', 'Preplanned'],
      dtype='object')

In [6]:
Data.head()

,LONCOD,LATCOD,CDCODE,year_x,school,city_x,state_x,address,urbanrural,race,...,State,School_Level,Location,During_School,Time_Period,First_Shot,Bullied,Domestic_Violence,Gang_Related,Preplanned
0,-75.584900,39.668100,1000.0,2009,William Penn High School,New Castle,Delaware,713 E Basin Rd,suburbtown,BLACK,...,PA,High,Cafeteria,Yes,NaN,NaN,No,Yes,No,No
1,-75.584900,39.668100,1000.0,2009,William Penn High School,New Castle,Delaware,713 E Basin Rd,suburbtown,BLACK,...,DE,High,Parking Lot,No,Sport Event,8:50 PM,No,No,No,No
2,-75.584900,39.668100,1000.0,2009,William Penn High School,New Castle,Delaware,713 E Basin Rd,suburbtown,BLACK,...,DE,High,Gym,No,Sport Event,8:30 PM,No,No,No,No
3,-83.113977,42.383593,NaN,2009,Central High School,Detroit,Michigan,2425 Tuxedo St,urban,NaN,...,IA,High,Bathroom,Yes,NaN,NaN,No,Yes,No,No
4,-83.113977,42.383593,NaN,2009,Central High School,Detroit,Michigan,2425 Tuxedo St,urban,NaN,...,MN,High,Inside School Building,Yes,Lunch,12:00 PM,No,No,No,No